### ISSUE TITLE
How to reinitialize page

### ISSUE THREAD

**Issue by momelnyk** [kikinteractive/app#119]
How to reinitialize page after it's html content has been completely rewritten?

Let say I have this basic structure

```html
<div class="app-page" data-page="home">
  <div class="app-topbar">
    <div class="app-title">Home</div>
  </div>

  <div class="app-content">
    <div class="app-section">
      <div class="app-button" data-target="page2">Go to Page 2</div>
    </div>
  </div>
</div>

<div class="app-page" data-page="page2">
  <div class="app-topbar">
    <div class="app-button left" data-back data-autotitle></div>
    <div class="app-title">Page 2</div>
  </div>

  <div class="app-content">
    Page 2 is lonely
  </div>
</div>
```

When I replace html content of `<div class="app-page" data-page="page2">` with the following code, back button stops working.

```javascript
App.controller('page2', function(page) {
  $(page).html('...HTML CONTENT SEE BELOW...');
});
```

HTML:
```html
  <div class="app-topbar">
    <div class="app-button left" data-back data-autotitle></div>
    <div class="app-title">Page 3</div>
  </div>

  <div class="app-content">
    Page 3 is lonely
  </div>
```

**Comment by muten84** [comment]
I solved this issue in my fork of this project changing the load behavior of pages. Check out at this link if interested https://github.com/muten84/app/commit/1aac5a31af5bcbea30dc7960bb30a27838c66b3f

**Comment by jairajs89** [comment]
Why do you need to replace the entire contents of a page at the start of its controller? Feels like that doesn't fit the usage pattern for pages/controllers

**Comment by muten84** [comment]
I agree with @jairajs89 my patch solves for the case of page reused and its content DOM changed so static preload mechanism was disabled. In any case controller initialization should be done every time after html download and loading of a page. Handler and listeners will be detached in page unload and will be reattached in page reload.

**Comment by momelnyk** [comment]
Guys, thank you for your quick and detailed replies. I was talking about dynamic loading of pages. I could not find how to reattach event listeners.

I generate html code of the page (app-page) on the server side instead of passing a json object and populating the page template with the json data.

**Comment by momelnyk** [comment]
So I used the following code, and it worked.

```javascript
el = $(html);
App.add('pageName', el);
App.load('pageName');
```

**Comment by muten84** [comment]
Does it work even if you load another dynamic content from server for a second page (with data-page attribute) and switch between them? I have to disable preload cause I had child pages loaded from server after App parses all the DOM with data-page attributes.

**Comment by jairajs89** [comment]
`App.add` can be called at any time to register a pages HTML description. So yes, you can dynamically fetch HTML from your server, call `App.add`, then be able to call `App.load` for that page whenever you want

**Comment by muten84** [comment]
I will try this approach too thank you.
