### ISSUE TITLE
Metrics api

### ISSUE THREAD

**Issue by necenzurat** [kikinteractive/app#68]
How you you enable/use the metrics API?

**Comment by jairajs89** [comment]
There is built-in page navigation tracking support for Google Analytics. Once you have included the Google Analytics code you can call `App.enableGoogleAnalytics()`. This will implicitly call Google Analytics' `trackPageview` functionality whenever you use `App.load` (or anything that makes the user view an App.js page). In the Google Analytics dashboard these will show up as regular pageviews as opposed to custom events.
