### ISSUE TITLE
Transition speed

### ISSUE THREAD

**Issue by brtwister2** [kikinteractive/app#71]
I don't understand how to change the transition speed. Is it possible?

**Comment by jairajs89** [comment]
Yes. Below is the syntax:

```js
var pageName    = 'nameOfPage';
var pageArgs    = { data: 'to', pass: 'the page' };
var loadOptions = {
    transition : 'fade',
    duration   : 700,
    easing     : 'ease-in-out'
};
App.load(pageName, pageArgs, loadOptions);
```

Valid `transition` values are listed here: https://github.com/kikinteractive/swapper#transition-types

`duration` is the time the transition should take in milliseconds.

`easing` is the CSS easing function to use. All default CSS easing functions are allowed (including custom cubic-bezier definitions).

**Comment by brtwister2** [comment]
Worked! Thank you!
