### ISSUE TITLE
Windows touch panel

### ISSUE THREAD

**Issue by poyoaki** [kikinteractive/app#81]
Hi,

Now I making my app using App.js, but I found issue on IE11 Windows8.1, page navigation don't work from touch panel.

/* Don't work */
 &lt;div class="app-button" data-target="next-page"&gt;&lt;/div&gt;

/* Don't work */
 &lt;div class="app-button"  id-"nextbtn"&gt;&lt;/div&gt;
$(page).find("#nextbtn").on('click', function() {
	App.load('next-page');	});

/* Work */
 &lt;div class="app-button"  id-"nextbtn"&gt;&lt;/div&gt;
$(page).find("#nextbtn").on('MSPointerDown', function() {
	App.load('next-page');	});

Can you help me how to add this event to App.js?

Thank you.

**Comment by jairajs89** [comment]
App.js only support Android 2.2+, iOS 4.3+. I believe the issue is at IE might not support the common touch event standard used by App.js (touchstart, touchmove, etc)

There currently isn't any roadmap for Windows support but we definitely open to contributions on that front

**Comment by poyoaki** [comment]
Hi jairajs89,
I investigated and tried ugly patch for Zepto.js and App.js. 
I see works on Windows tab...

/* app.js 3.0.1 */
App._Pages = ...
	function startPageGeneration ...
		Utils.forEach(
			page.querySelectorAll('.app-button'),
			function (button) {
				if (button.getAttribute('data-no-click') !== null) {
					return;
				}
				Clickable(button);
/* added start : copy of 'click' handler*/
				button.addEventListener('MSPointerDown', function () {
					var target     = button.getAttribute('data-target'),
						targetArgs = button.getAttribute('data-target-args'),
						back       = (button.getAttribute('data-back') !== null),
						manualBack = (button.getAttribute('data-manual-back') !== null),
						args;

					try {
						args = JSON.parse(targetArgs);
					} catch (err) {}
					if ((typeof args !== 'object') || (args === null)) {
						args = {};
					}

					if (!back && !target) {
						return;
					}
					if (back && manualBack) {
						return;
					}

					var clickableClass = button.getAttribute('data-clickable-class');
					if (clickableClass) {
						button.disabled = true;
						// error on IE9 here.
						button.classList.add(clickableClass);
					}

					if (back) {
						App.back(finish);
					}
					else if (target) {
						App.load(target, args, {}, finish);
					}

					function finish () {
						if (clickableClass) {
							button.disabled = false;
							button.classList.remove(clickableClass);
						}
					}

				}, false);
/* added end */

// Zepto 1.1.6 event
  function add(element, events, fn, data, selector, delegator, capture){ 
...
      if ('addEventListener' in element)
		{
        element.addEventListener(realEvent(handler.e), handler.proxy, eventCapture(handler, capture))
/* added */
		if (handler.e == 'click')
        element.addEventListener(realEvent('MSPointerDown'), handler.proxy, eventCapture(handler, capture))
/* added end */
		}
    }) 

Thanks,
