### ISSUE TITLE
returning false in appBeforeBack

### ISSUE THREAD

**Issue by jackread** [kikinteractive/app#85]
returning false in appBeforeBack locks the back button in the active state.

Is that intentional?

The use case is...
I have a controller with 3-4 steps. I want the back button to cycle back through all the steps before navigating to the previous page.

e.g. 
```
$(page).on("appBeforeBack", function() {
    if (prevStep()) return false;
});
```

**Comment by jairajs89** [comment]
Definitely not intentional, was a bug. Fixed in v3.0.3
